# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
         algorithm : sha512
        encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            #pattern:    .*
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    false
                always_use_default_target_path : true
                default_target_path: fos_user_security_login
                check_path:     fos_user_security_check
                failure_path:   fos_user_security_login
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/list, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/change-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/collaborateur, roles: ROLE_USER }
        - { path: ^/sousTraitant, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
